### ISSUE TITLE
Holes in Dreadnought sprite

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky-high-dpi#12]
I thought you said you would remove them. Or at least from the not-high-dpi sprites.

**Comment by Amazinite** [comment]
@LocalGod79 notice the two white areas within the bounds of the ship.
![dreadnought 2x](https://cloud.githubusercontent.com/assets/17688683/17842874/439222e0-67f5-11e6-81ed-1729bbc832db.png)

**Comment by LocalGod79** [comment]
it happens in a couple of places - near the central "spines" as well as the engines...

**Comment by Amazinite** [comment]
Circled the areas.
![439222e0-67f5-11e6-81ed-1729bbc832db](https://cloud.githubusercontent.com/assets/17688683/17855797/906fb886-6848-11e6-89bd-f4d6ec611228.png)

**Comment by endless-sky** [comment]
Fixed in 2a52e99.
