### ISSUE TITLE
No @2x Skylance Projectile

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky-high-dpi#13]
Title says it all.

**Comment by Bladewood** [comment]
I think Michael left that out because placeholders, so I never mentioned it.

**Comment by endless-sky** [comment]
For anything that doesn't have sharp edges at 1x, I generally don't bother to provide 2x graphics. That is, if linear interpolation will produce an image almost identical to what the full 2x image would be, there's no point in providing that 2x image.

**Comment by Amazinite** [comment]
Alright.
