### ISSUE TITLE
3D Model sources?

### ISSUE THREAD

**Issue by MoffKalast** [endless-sky/endless-sky-high-dpi#143]
Hi there!

Given that the sprites in the game are rendered in both top-down and side-front angles (for the shop icons) leads me to assume these aren't hand drawn but rendered 3D models.  If I'm right about that, is there a repository of them or does somebody keep them somewhere? I haven't found it here on github.

I'm asking because frankly it would be rather cool to 3D print some of these ships. One of my hobbies is finding and repairing spaceship meshes for printing (and then printing and painting them ofc), so I'd be up to prepare at least a few of the more notable ones for printing and put them up on thingiverse for everyone else if it's alright with you guys.

Thanks :)

**Comment by Zitchas** [comment]
Greetings!

Yes, you are correct. Virtually all the ships in the game are actual 3d models from which the top view and thumbnail views are rendered. 

The official asset repository can be located here, although it is out of date compared to what is actually in the game:
https://drive.google.com/drive/folders/0B9aK8dG39P29fkdBeUJjSXJYVDdjMEpkOXh3T1NDekFYaTEtbkdTdzVwX2NTUWVVT3BUWVk

The remaining assets should be accessed via the following issue:
https://github.com/endless-sky/endless-sky/issues/4571

3d printing ships would be really cool to see. I (and I'm sure many others) would be very interested in seeing more about the process and results of 3d printing these ships.

For general questions, I would recommend visiting the discord server: https://discord.gg/ZeuASSx

**Comment by MoffKalast** [comment]
Oh great, thanks! I'll keep you guys posted about my progress on discord. 👍
