### ISSUE TITLE
libpng warning: Interlace handling should be turned on when using png_read_image

### ISSUE THREAD

**Issue by solsticesolutions** [endless-sky/endless-sky-high-dpi#184]
I am getting this error quite often. My libpng is up-to-date, some sources I see online say using different png types or non-interlaced images will resolve this.

Anyone else have this issue, or a simple fix?

**Comment by MCOfficer** [comment]
It's just a warning, so no fix is necessary for the game to function as intended. Still, what's your libpng version, and if possible, can you tell which images you get this warning for?
