### ISSUE TITLE
Non-high-DPI sprites?

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky-high-dpi#21]
https://github.com/endless-sky/endless-sky/commit/d51d5dada3ffaa1de31a3c2e6f87a2acb894d60b

Also, why do features on the star map (galaxy background, region labels) not have their own high DPI sprites?

**Comment by endless-sky** [comment]
In general, I decide on a case-by-case basis depending on how big the sprite is (i.e. how much memory it would take up) and how important it is for it to have super-sharp edges.

In the case of the Void Sprites, they need to be a bit fuzzy at high resolution to hide the limited number of animation frames. And for the map labels, they're supposed to blend in to the background, so a bit of fuzziness is not a bad thing.
