### ISSUE TITLE
Missing @2x projectiles

### ISSUE THREAD

**Issue by Nescio0** [endless-sky/endless-sky-high-dpi#55]
There are no `images/projectile/` * `@2x.png` versions of the following weapons:
* attractor
* detainer
* fire-lance
* flamethrower
* ion rain
* moonbeam
* plasma
* proton
* rainbow
* repulsor
* skylance

**Comment by endless-sky** [comment]
My general rule is that if the 1x sprite is intentionally blurry, there's no point in adding a 2x variant. (Or, another way of thinking about it: if the 2x variant would be visually indistinguishable from a linearly interpolated version of the 1x variant, there's no point in it being supplied.) Many of those would fall into that category.
