### ISSUE TITLE
Add endless-sky-3d-models LFS-enabled respository for storing 3d artwork

### ISSUE THREAD

**Issue by petervdmeer** [endless-sky/endless-sky-high-dpi#81]
This is a request to add a (Git LFS (Large File Support) enabled) endless-sky-3dmodels or endless-sky-artwork repository that stores the 3D models of ships and outfits and other 3D original models in the game.

Models currently appear to be stored in Google drive, but having a single set of tools (Git, Github) to upload all relevant source data would decrease the risk of models (or intermediate versions of models) getting lost.

This request can probably only be handled by @endless-sky, because I think he is the only one with permissions to create repositories here.

**Comment by mOctave** [comment]
Now that we have (and have had for quite some time) an asset repo, can this be closed?

**Comment by Zitchas** [comment]
Yes, I think so. If nothing else, pretty much everything is stored in an asset repository here, anyway.
